### ISSUE TITLE
Bales not Counting in sales

### ISSUE THREAD

**Issue by WickedSoul14** [GMNGjoy/FS25_ContractBoost#10]
So if I do a bale wrapping contract and than take the bales back to my farm to turn into silage when I later go sell the bales I don't get credit for them. It's as if the game doesn't recognize the bales I've obtained from the contract as my own and not giving me credit for selling them later on.

**Comment by GMNGjoy** [comment]
This mod does NOT currently allow you to pick up bales from baling contracts of any kind. It SPECIFICALLY calls out Mowing missions

> Allow collecting grass from mowing missions

This mean MOWING missions only, not baling missions of any kind. That said, I'm going to try to allow bales to be collected / owned by you, that's next on my list of features to add, but it'll be a few weeks. I'm going to close this issue since it's already on the list!

**Comment by WickedSoul14** [comment]
I'm sorry I miss read that part keep up the great work I love the mod.
