### ISSUE TITLE
Reward Factor is 0.5 not 1.5

### ISSUE THREAD

**Issue by KingCobraa-25** [GMNGjoy/FS25_ContractBoost#19]
Without any modifications made, I installed the mod and was scrolling thru the ContractBoose.xml file and noticed that the reward factor is 0.5, not 1.5. To be sure, I launched the game and found out that sure enough, all contract prices were even lower than without the mod.

Just FYI as there may be some who don't want to edit any settings files, and just want it to "work" at the stated 50% buff that's advertised.

**Comment by GMNGjoy** [comment]
THANK YOU! I must have somehow committed a change while researching #8, and didn't realize that I had changed the default file instead of my own. I've released [1.0.2.1](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.2.1) with that setting fixed.

That said - the `modSettings/ContractBoost.xml` file only gets written once, when you use the mod for the first time. Since your system already has the wrong value, you'll have to edit the value to the `1.5` default value on your own system should you choose.
