### ISSUE TITLE
[FEATURE] Ability to filter harvest missions by fruittypes

### ISSUE THREAD

**Issue by aurelien2023** [GMNGjoy/FS25_ContractBoost#35]
**Is your feature request related to a problem? Please describe.**
Too many harvest contracts for vegetables or Root crops

**Describe the solution you'd like**
Could limit the number of harvest missions for:

-  Vegetables
-  Root crops
-  Other harvest missions

**Additional context**
More than 25 harvest missions, but none for crops other than Vegetables or Root crops.
Other crops also have more limited harvesting periods in the calendar, so contracts for them can be easily missed.

**Comment by GMNGjoy** [comment]
I like the idea, I'll see what I can do! as of right now, all the harvesting contracts are bundled together which isn't something I can change. I'd suggest for now - you can increase the number of harvest contracts by changing the _Maximum Harvest Contracts_ to something large (ie: 25+), so that at least existing root crop contracts don't prevent those harvest contracts from showing up.

Someone else also suggested a feature to "refuse" a contract, thereby removing it from the queue, and potentially allowing others to be generated, which may serve the same purpose. That's on my list to add if I can figure out a way to do it.

**Comment by aurelien2023** [comment]
Yes, I know it's Giants' way of mixing all the crops together. I hope you can find a way to use "fruittypecategories" or something similar.
I also hope that refusing a contract will not cause the game to regenerate it again while the crop is still ready for harvest, because when I try resetting and refreshing contracts with BetterContracts, the same ones often regenerate.

**Comment by Mmtrx** [comment]
@aurelien2023 : since you also voiced that idea under BetterContracts, I'd like to pursue that in a next release. If that 's ok with @GMNGjoy 😉

**Comment by aurelien2023** [comment]
I'll be very please to see you work together to achieve what's Giants didn't do in many years of developement of FS25... 🥇

**Comment by GMNGjoy** [comment]
> @aurelien2023 : since you also voiced that idea under BetterContracts, I'd like to pursue that in a next release. If that 's ok with @GMNGjoy 😉

By all means, go for it!

**Comment by GMNGjoy** [comment]
After aligning with @Mmtrx, I'm going to defer this feature to https://github.com/Mmtrx/FS25_BetterContracts

**Comment by GMNGjoy** [comment]
I ended up finding a solution for this that still aligns within this mod, in [1.0.8.0](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.8.0).
